# MIT License - Copyright (c) 2018 GitHub, Inc. and contributors
# https://github.com/actions/upload-artifact
name: 'Upload a Build Artifact'
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

description: 'Upload a build artifact that can be used by subsequent workflow steps'
author: 'Daniel Clough'
inputs: 
  name:
    description: 'Rust Quizzes'
    default: 'rq'
  path:
    description: 'rq, the Rust Quizzes binary'
    required: true
  if-no-files-found:
    description: >
      Available Options:
        warn: Output a warning but do not fail the action
        error: Fail the action with an error message
        ignore: Do not output any warnings or errors, the action does not fail
    default: 'warn'
  retention-days:
    description: >
      Duration after which artifact will expire in days. 0 means using default retention.
      Minimum 1 day.
      Maximum 90 days unless changed from the repository settings page.
runs:
  using: 'node16'
  main: 'dist/index.js'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      with:
        name: rq
        path: rust-puzzles/target/release/rq